### ISSUE TITLE
runtime exception java.lang.NoClassDefFoundError: javax/jms/JMSException.

### ISSUE THREAD

**Issue by mizie** [IBMStreams/streamsx.messaging#242] opened 2016-06-08 05:08 UTC
Hi

I'm developing a program for sending the proceed data from Infosphere Streams (version 3.2.1) to Active MQ but I am getting runtime exception java.lang.NoClassDefFoundError: javax/jms/JMSException.

toolkit name : streamx.messaging.toolkits-0.8.1-20151030-1803

08 Jun 2016 20:53:29.062 [28491] ERROR #splapptrc,J[0],P[0],toAMQ,spl_javaop M[JavaOp.cpp:trace:82]  - com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:292)
Exception in thread "Thread-8" java.lang.NoClassDefFoundError: javax.jms.JMSException
        at java.lang.J9VMInternals.verifyImpl(Native Method)
        at java.lang.J9VMInternals.verify(J9VMInternals.java:94)
        at java.lang.J9VMInternals.initialize(J9VMInternals.java:171)
        at com.ibm.streamsx.messaging.jms.JMSSink.initialize(JMSSink.java:339)
        at com.ibm.streams.operator.internal.runtime.api.OpAdapter.operatorInitialize(OpAdapter.java:92)
        at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:616)
        at com.ibm.streams.operator.internal.jni.JNIBridge.<init>(JNIBridge.java:292)
Caused by: java.lang.ClassNotFoundException: javax.jms.JMSException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:599)
        at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:760)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:737)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:707)
        ... 7 more

could someone help me.

**Comment by conglisc** [comment] 2016-06-11 18:25
Hi Mizie,

Most likely this issue is caused by the instance not having required env variables. You need to stop instance and make sure the STREAMS_MESSAGING_AMQ_HOME env variable is set, then start your instance and run your app.

Here is another doc that can help you review your setup http://ibmstreams.github.io/streamsx.documentation/docs/4.1/messaging/jms-operators-getting-started/

**Comment by schubon** [comment] 2019-03-25 16:55
As @conglisc already stated this is a configuration problem that is resolved by introducing the environment variable STREAMS_MESSAGING_AMQ_HOME, pointig to the installation location of Active MQ, or STREAMS_MESSAGING_WMQ_HOME, pointig to the installation location of WMQ.

But there is one ugly pitfall here:
When you create these environment variable already configured domains and instances still will not know it, you must restart your domain (and the instance) to let Streams know of the new value. A restart of the job is not enough.

**Comment by schubon** [comment] 2019-03-25 16:56
Closing as this is a system configuration issue.

**Closed by schubon** 2019-03-25 16:56 UTC
Labels: bug, jms
