### ISSUE TITLE
Cleansession for MQTT operators

### ISSUE THREAD

**Issue by chantalokh** [IBMStreams/streamsx.messaging#209] opened 2016-03-17 15:39 UTC
Good morning,

We have a need to set sometimes the cleansession to false (for durable subscriptions and other needs), but i saw that it is forced to true,
line 52 of MqttClientWrapper.java, the clean session is always set to true
`conOpt.setCleanSession(true);` 
have you planned to put it as parameter of the operator?
Thanks
Amir

**Comment by ddebrunner** [comment] 2016-03-18 23:53
Duplicate of #61

**Comment by ddebrunner** [comment] 2016-05-08 23:31
This is probably a better description of the issue. I had previously thought that clean session was not supported and the operators default to durable, but they only support clean at the moment.

**Comment by schubon** [comment] 2021-03-22 11:09
Customers are already using the new toolkit https://github.com/IBMStreams/streamsx.mqtt

**Closed by schubon** 2021-03-22 11:09 UTC
Labels: contribution, mqtt, wontfix
